window.WEBWIN_APPS = [
  {
    id: 'vscodium',
    name: 'VSCodium',
    publisher: 'VSCodium Team',
    category: 'Development',
    license: 'MIT',
    platforms: 'Windows x64',
    tags: ['editor', 'git', 'typescript', 'coding'],
    summary: 'Telemetry-free Visual Studio Code build for Windows developers.',
    description: 'VSCodium provides the familiar VS Code experience without Microsoft telemetry. It is ideal for coding, scripting, web development, and extension-based workflows.',
    website: 'https://vscodium.com/',
    repository: 'https://github.com/VSCodium/vscodium',
    downloadUrl: 'https://github.com/VSCodium/vscodium/releases/latest/download/VSCodiumSetup-x64.exe'
  },
  {
    id: 'libreoffice',
    name: 'LibreOffice',
    publisher: 'The Document Foundation',
    category: 'Productivity',
    license: 'MPL-2.0',
    platforms: 'Windows x64',
    tags: ['office', 'documents', 'spreadsheet', 'presentation'],
    summary: 'Full office suite with writer, calc, impress, and more.',
    description: 'LibreOffice is a complete free office suite for documents, spreadsheets, presentations, diagrams, and databases. It is one of the strongest open-source productivity stacks for Windows.',
    website: 'https://www.libreoffice.org/',
    repository: 'https://github.com/LibreOffice/core',
    downloadUrl: 'https://download.documentfoundation.org/libreoffice/stable/'
  },
  {
    id: 'gimp',
    name: 'GIMP',
    publisher: 'GIMP Team',
    category: 'Graphics',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['image', 'photo', 'editing', 'design'],
    summary: 'Advanced image editor for retouching, illustration, and compositing.',
    description: 'GIMP is a mature open-source graphics editor suited to image manipulation, asset creation, retouching, and creative workflows.',
    website: 'https://www.gimp.org/',
    repository: 'https://github.com/GNOME/gimp',
    downloadUrl: 'https://www.gimp.org/downloads/'
  },
  {
    id: 'inkscape',
    name: 'Inkscape',
    publisher: 'Inkscape Project',
    category: 'Graphics',
    license: 'GPL-2.0',
    platforms: 'Windows x64',
    tags: ['vector', 'svg', 'illustration', 'ui'],
    summary: 'Open-source vector editor for SVG design and illustration.',
    description: 'Inkscape is built for vector drawing, icon creation, interface art, logos, and SVG editing with a strong plugin ecosystem.',
    website: 'https://inkscape.org/',
    repository: 'https://gitlab.com/inkscape/inkscape',
    downloadUrl: 'https://inkscape.org/release/'
  },
  {
    id: 'krita',
    name: 'Krita',
    publisher: 'KDE',
    category: 'Graphics',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['painting', 'drawing', 'art', 'tablet'],
    summary: 'Digital painting studio for illustration, concept art, and comics.',
    description: 'Krita is a focused digital art application optimized for painting workflows, brushes, tablets, concept art, and comics.',
    website: 'https://krita.org/',
    repository: 'https://invent.kde.org/graphics/krita',
    downloadUrl: 'https://krita.org/en/download/krita-desktop/'
  },
  {
    id: 'blender',
    name: 'Blender',
    publisher: 'Blender Foundation',
    category: '3D',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['3d', 'animation', 'modeling', 'rendering'],
    summary: 'Professional open-source 3D suite for modeling and rendering.',
    description: 'Blender covers modeling, animation, rendering, compositing, simulation, rigging, sculpting, and video editing in one desktop package.',
    website: 'https://www.blender.org/',
    repository: 'https://github.com/blender/blender',
    downloadUrl: 'https://www.blender.org/download/'
  },
  {
    id: 'obs',
    name: 'OBS Studio',
    publisher: 'OBS Project',
    category: 'Media',
    license: 'GPL-2.0',
    platforms: 'Windows x64',
    tags: ['streaming', 'recording', 'capture', 'broadcast'],
    summary: 'Streaming and recording suite for creators and live production.',
    description: 'OBS Studio is the open-source standard for screen capture, streaming scenes, overlays, live broadcasting, and recording workflows.',
    website: 'https://obsproject.com/',
    repository: 'https://github.com/obsproject/obs-studio',
    downloadUrl: 'https://obsproject.com/download'
  },
  {
    id: 'vlc',
    name: 'VLC',
    publisher: 'VideoLAN',
    category: 'Media',
    license: 'GPL-2.0',
    platforms: 'Windows x64',
    tags: ['video', 'audio', 'player', 'codec'],
    summary: 'Universal media player with strong codec support.',
    description: 'VLC plays almost any media format locally or over networks and remains one of the most reliable media tools on Windows.',
    website: 'https://www.videolan.org/vlc/',
    repository: 'https://code.videolan.org/videolan/vlc',
    downloadUrl: 'https://www.videolan.org/vlc/download-windows.html'
  },
  {
    id: 'audacity',
    name: 'Audacity',
    publisher: 'Audacity Team',
    category: 'Audio',
    license: 'GPL-2.0',
    platforms: 'Windows x64',
    tags: ['audio', 'recording', 'editing', 'podcast'],
    summary: 'Audio editor and recorder for podcasts, cleanup, and mastering.',
    description: 'Audacity is a powerful audio editor with multitrack workflows, effects, plugins, recording features, and restoration tools.',
    website: 'https://www.audacityteam.org/',
    repository: 'https://github.com/audacity/audacity',
    downloadUrl: 'https://github.com/audacity/audacity/releases/latest'
  },
  {
    id: 'keepassxc',
    name: 'KeePassXC',
    publisher: 'KeePassXC Team',
    category: 'Security',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['password', 'vault', 'security', 'privacy'],
    summary: 'Offline password manager with encrypted vault support.',
    description: 'KeePassXC stores passwords in encrypted local databases, supports generators, browser integration, and hardware-backed workflows.',
    website: 'https://keepassxc.org/',
    repository: 'https://github.com/keepassxreboot/keepassxc',
    downloadUrl: 'https://keepassxc.org/download/'
  },
  {
    id: 'bitwarden',
    name: 'Bitwarden Desktop',
    publisher: 'Bitwarden',
    category: 'Security',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['password', 'sync', 'security', 'vault'],
    summary: 'Open-source password manager with cloud sync support.',
    description: 'Bitwarden Desktop gives access to secure vault storage, password generation, and synchronized secrets across devices.',
    website: 'https://bitwarden.com/download/',
    repository: 'https://github.com/bitwarden/clients',
    downloadUrl: 'https://bitwarden.com/download/'
  },
  {
    id: '7zip',
    name: '7-Zip',
    publisher: 'Igor Pavlov',
    category: 'Utilities',
    license: 'LGPL-2.1',
    platforms: 'Windows x64',
    tags: ['archive', 'compression', 'files', 'extract'],
    summary: 'Fast archive manager with 7z, zip, tar, and more.',
    description: '7-Zip is a lightweight compression tool for creating and extracting many archive formats with a very strong compression ratio.',
    website: 'https://www.7-zip.org/',
    repository: 'https://github.com/ip7z/7zip',
    downloadUrl: 'https://www.7-zip.org/download.html'
  },
  {
    id: 'sharex',
    name: 'ShareX',
    publisher: 'ShareX Team',
    category: 'Utilities',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['screenshot', 'screen recording', 'upload', 'capture'],
    summary: 'Advanced screenshot and screen capture utility for Windows.',
    description: 'ShareX handles screenshots, GIF capture, workflows, upload presets, OCR actions, and automation around image capture.',
    website: 'https://getsharex.com/',
    repository: 'https://github.com/ShareX/ShareX',
    downloadUrl: 'https://getsharex.com/downloads'
  },
  {
    id: 'powertoys',
    name: 'Microsoft PowerToys',
    publisher: 'Microsoft',
    category: 'Utilities',
    license: 'MIT',
    platforms: 'Windows x64',
    tags: ['windows', 'launcher', 'tiling', 'tools'],
    summary: 'Productivity utilities for advanced Windows users.',
    description: 'PowerToys adds launcher, window tiling, keyboard tools, image resizing, mouse utilities, and many focused Windows productivity modules.',
    website: 'https://learn.microsoft.com/windows/powertoys/',
    repository: 'https://github.com/microsoft/PowerToys',
    downloadUrl: 'https://github.com/microsoft/PowerToys/releases/latest'
  },
  {
    id: 'notepadpp',
    name: 'Notepad++',
    publisher: 'Don Ho',
    category: 'Development',
    license: 'GPL-3.0',
    platforms: 'Windows x64',
    tags: ['editor', 'text', 'code', 'lightweight'],
    summary: 'Fast text and source-code editor optimized for Windows.',
    description: 'Notepad++ is a lightweight editor with syntax highlighting, macros, plugins, and a strong reputation for speed on Windows.',
    website: 'https://notepad-plus-plus.org/',
    repository: 'https://github.com/notepad-plus-plus/notepad-plus-plus',
    downloadUrl: 'https://notepad-plus-plus.org/downloads/'
  },
  {
    id: 'godot',
    name: 'Godot Engine',
    publisher: 'Godot Foundation',
    category: 'Game Development',
    license: 'MIT',
    platforms: 'Windows x64',
    tags: ['game engine', '2d', '3d', 'dev'],
    summary: 'Open-source game engine for 2D and 3D projects.',
    description: 'Godot provides a full editor, scripting system, scene model, asset pipeline, and export toolchain for game development.',
    website: 'https://godotengine.org/',
    repository: 'https://github.com/godotengine/godot',
    downloadUrl: 'https://godotengine.org/download/windows/'
  }
];
